### ISSUE TITLE
Vertical and Horizontal Layout Doesn't Hold in All Cases

### ISSUE THREAD

**Issue by sketchytech** [FlexMonkey/StackView#1]
If you are in landscape orientation and press the "grey" button to conceal grey, green and yellow, and then change orientation, before pressing grey again, then grey, green and yellow take on the same orientation as all the other colours and do not reset until blue, for example, is taken out.

I've also had an instance that I can't reproduce where a white gap if left when some of the colours are hidden.

**Comment by FlexMonkey** [comment]
Hi,

I've experienced a few glitches too. I suspect this is because both the SDK and target OS are both beta, but I'll file a radar later.

Cheers,
Simon

**Comment by sketchytech** [comment]
I expect so, I'm having fun playing around with it. It's a great starting point for working with UIStackViews. I'll close this issue for now since I know this is more an experiment than a framework or app.

**Comment by FlexMonkey** [comment]
Cheers :)

Of course, if you need something similar for use with iOS 8, my own Shinpuru Layout offers the same sort of functionality: https://github.com/FlexMonkey/ShinpuruLayout

Simon
